# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d976dee824bad3a37ca3ea802b97f71a8ad69948148586b76b39a1aa7e1cb93ff81799dd278f805d1ec91d628058d42951d45eec1b050a1d0876dee10079a8

test:
  secret_key_base: 4573b7213ac166e6d3c13d23659e38a8e7a114c44684737b315a74063d4b3d0a959741cf855e8f816a8e4ced7a3a99b75a4301f4febf318fc11d4cce271a7ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
